-- Persistent preference memory tables

create table if not exists public.knowledge_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  agent text not null,
  title text not null,
  content text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists knowledge_entries_user_agent_idx
  on public.knowledge_entries(user_id, agent, enabled);

create table if not exists public.implicit_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  agent text not null,
  key text not null,
  value_json jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, agent, key)
);

create index if not exists implicit_preferences_updated_idx
  on public.implicit_preferences(user_id, agent, updated_at desc);

create table if not exists public.preference_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  agent text not null,
  key text not null,
  observed_json jsonb not null,
  weight double precision not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists preference_events_user_agent_idx
  on public.preference_events(user_id, agent, created_at desc);

create table if not exists public.knowledge_suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  agent text not null,
  title text not null,
  content text not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists knowledge_suggestions_user_agent_idx
  on public.knowledge_suggestions(user_id, agent, created_at desc);
